/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventana.login.URL;
import static ventana.login.mysql_pass;
import static ventana.login.mysql_user;
import static ventana.login.user_numeric_level;

/**
 *
 * @author Ale
 */
public class admin_tools extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public admin_tools() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/user2.png")).getImage());
        this.setLocationRelativeTo(null);
        if(user_numeric_level==2 ||user_numeric_level==3){
            registrar_profesores.setVisible(false);
            cambiar_permisos.setVisible(false);
            modificar_registros.setVisible(false);
        }if (user_numeric_level==3){
            registrar_alumnos.setVisible(false);
        }
        
    }

    public static Connection getConection() {
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);

        } catch (Exception e) {
            System.out.println(e);

        }
        return con;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panel_perfil = new javax.swing.JPanel();
        user_icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        modificar_registros = new javax.swing.JButton();
        cambiar_permisos = new javax.swing.JButton();
        registrar_profesores = new javax.swing.JButton();
        editar_datos = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        registrar_alumnos = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(565, 730));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_perfil.setBackground(new java.awt.Color(204, 204, 204));
        panel_perfil.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        panel_perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N
        panel_perfil.add(user_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, -1));

        jPanel2.setBackground(new java.awt.Color(72, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificar_registros.setBackground(new java.awt.Color(102, 102, 102));
        modificar_registros.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        modificar_registros.setForeground(new java.awt.Color(255, 255, 255));
        modificar_registros.setText("MODIFICAR REGISTROS");
        modificar_registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_registrosActionPerformed(evt);
            }
        });
        jPanel2.add(modificar_registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 400, 50));

        cambiar_permisos.setBackground(new java.awt.Color(102, 102, 102));
        cambiar_permisos.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        cambiar_permisos.setForeground(new java.awt.Color(255, 255, 255));
        cambiar_permisos.setText("CAMBIAR PERMISOS");
        cambiar_permisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiar_permisosActionPerformed(evt);
            }
        });
        jPanel2.add(cambiar_permisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 400, 50));

        registrar_profesores.setBackground(new java.awt.Color(102, 102, 102));
        registrar_profesores.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        registrar_profesores.setForeground(new java.awt.Color(255, 255, 255));
        registrar_profesores.setText("REGISTRAR PROFESORES");
        registrar_profesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_profesoresActionPerformed(evt);
            }
        });
        jPanel2.add(registrar_profesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 400, 50));

        editar_datos.setBackground(new java.awt.Color(102, 102, 102));
        editar_datos.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        editar_datos.setForeground(new java.awt.Color(255, 255, 255));
        editar_datos.setText("EDITAR DATOS PERSONALES");
        editar_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_datosActionPerformed(evt);
            }
        });
        jPanel2.add(editar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 400, 50));

        aceptar.setBackground(new java.awt.Color(50, 0, 0));
        aceptar.setFont(new java.awt.Font("King", 1, 24)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("VOLVER");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, -1, 60));

        registrar_alumnos.setBackground(new java.awt.Color(102, 102, 102));
        registrar_alumnos.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        registrar_alumnos.setForeground(new java.awt.Color(255, 255, 255));
        registrar_alumnos.setText("REGISTRAR ALUMNOS");
        registrar_alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_alumnosActionPerformed(evt);
            }
        });
        jPanel2.add(registrar_alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 400, 50));

        panel_perfil.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 600, 670));

        getContentPane().add(panel_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        main main = new main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aceptarActionPerformed

    private void editar_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_datosActionPerformed
        editar_personales main = new editar_personales();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editar_datosActionPerformed

    private void registrar_profesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_profesoresActionPerformed
        registrar_profesores main = new registrar_profesores();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrar_profesoresActionPerformed

    private void cambiar_permisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiar_permisosActionPerformed
        cambiar_permisos main = new cambiar_permisos();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cambiar_permisosActionPerformed

    private void registrar_alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_alumnosActionPerformed
        registrar_alumnos main = new registrar_alumnos();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrar_alumnosActionPerformed

    private void modificar_registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_registrosActionPerformed
        modificar_registros main = new modificar_registros();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modificar_registrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_tools().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cambiar_permisos;
    private javax.swing.JButton editar_datos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modificar_registros;
    private javax.swing.JPanel panel_perfil;
    private javax.swing.JButton registrar_alumnos;
    private javax.swing.JButton registrar_profesores;
    private javax.swing.JLabel user_icon;
    // End of variables declaration//GEN-END:variables
}
