/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import com.mysql.jdbc.Connection;
import static java.lang.Integer.parseInt;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventana.login.URL;
import static ventana.login.mysql_pass;
import static ventana.login.mysql_user;

/**
 *
 * @author Ale
 */
public class cambiar_permisos extends javax.swing.JFrame {

    /**
     * Creates new form cambiar_permisos
     */
    private int nivel = 1;

    public cambiar_permisos() {
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/user2.png")).getImage());
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_niveles = new javax.swing.ButtonGroup();
        bg_entrada = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        data_field = new javax.swing.JTextField();
        rb_nombre = new javax.swing.JRadioButton();
        rb_administrador = new javax.swing.JRadioButton();
        rb_coordinador = new javax.swing.JRadioButton();
        b_volver = new javax.swing.JButton();
        b_aceptar = new javax.swing.JButton();
        rb_profesor = new javax.swing.JRadioButton();
        rb_no = new javax.swing.JRadioButton();

        bg_niveles.add(rb_profesor);
        bg_niveles.add(rb_coordinador);
        bg_niveles.add(rb_administrador);

        bg_entrada.add(rb_nombre);
        bg_entrada.add(rb_no);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data_field.setBackground(new java.awt.Color(255, 255, 255));
        data_field.setFont(new java.awt.Font("Anonymous Pro", 2, 24)); // NOI18N
        data_field.setForeground(new java.awt.Color(0, 0, 0));
        data_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_field.setText("dato");
        data_field.setMargin(new java.awt.Insets(0, 10, 0, 0));
        data_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                data_fieldFocusGained(evt);
            }
        });
        jPanel2.add(data_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 482, 52));

        rb_nombre.setBackground(new java.awt.Color(0, 51, 55));
        rb_nombre.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        rb_nombre.setForeground(new java.awt.Color(255, 255, 255));
        rb_nombre.setText("Nombre completo");
        jPanel2.add(rb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        rb_administrador.setBackground(new java.awt.Color(0, 51, 55));
        rb_administrador.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        rb_administrador.setForeground(new java.awt.Color(255, 255, 255));
        rb_administrador.setText("Administrador");
        rb_administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_administradorActionPerformed(evt);
            }
        });
        jPanel2.add(rb_administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        rb_coordinador.setBackground(new java.awt.Color(0, 51, 55));
        rb_coordinador.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        rb_coordinador.setForeground(new java.awt.Color(255, 255, 255));
        rb_coordinador.setText("Coordinador");
        rb_coordinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_coordinadorActionPerformed(evt);
            }
        });
        jPanel2.add(rb_coordinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        b_volver.setBackground(new java.awt.Color(0, 0, 0));
        b_volver.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        b_volver.setForeground(new java.awt.Color(255, 255, 255));
        b_volver.setText("VOLVER");
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });
        jPanel2.add(b_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, 50));

        b_aceptar.setBackground(new java.awt.Color(51, 0, 0));
        b_aceptar.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        b_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        b_aceptar.setText("ACEPTAR");
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(b_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 230, 50));

        rb_profesor.setBackground(new java.awt.Color(0, 51, 55));
        rb_profesor.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        rb_profesor.setForeground(new java.awt.Color(255, 255, 255));
        rb_profesor.setSelected(true);
        rb_profesor.setText("Profesor");
        rb_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_profesorActionPerformed(evt);
            }
        });
        jPanel2.add(rb_profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        rb_no.setBackground(new java.awt.Color(0, 51, 55));
        rb_no.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        rb_no.setForeground(new java.awt.Color(255, 255, 255));
        rb_no.setSelected(true);
        rb_no.setText("n° empleado");
        jPanel2.add(rb_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_fieldFocusGained
        data_field.setText("");
    }//GEN-LAST:event_data_fieldFocusGained

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        admin_tools main = new admin_tools();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b_volverActionPerformed

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
        aceptacion();
    }//GEN-LAST:event_b_aceptarActionPerformed

    private void rb_administradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_administradorActionPerformed
        nivel = 1;
    }//GEN-LAST:event_rb_administradorActionPerformed

    private void rb_coordinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_coordinadorActionPerformed
        nivel = 2;
    }//GEN-LAST:event_rb_coordinadorActionPerformed

    private void rb_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_profesorActionPerformed
        nivel = 3;
    }//GEN-LAST:event_rb_profesorActionPerformed

    private void aceptacion() {

        if (rb_no.isSelected()) {
            loaded(parseInt(data_field.getText()));
        } else {
            loaded(extraLoaded());
        }
        
        JOptionPane.showMessageDialog(null, "¡Privilegios cambiados exitosamente!");
    }

    private int extraLoaded(){
        int no = -1;
        Connection con;
        PreparedStatement st = null;
        ResultSet rs;
        String[] profesor = data_field.getText().split(" ");

        try{
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
                
                switch(profesor.length)
                {
                    case 1:
                        st = (PreparedStatement) con.prepareStatement("select noEmpleado from profesor where nombre like ?");
                        st.setString(1, "%" + profesor[0] + "%");
                        break;
                    case 2:
                        st = (PreparedStatement) con.prepareStatement("select noEmpleado from profesor where nombre like ? or apellido_p like ?");
                        st.setString(1, "%" + profesor[0] + "%");
                        st.setString(2, "%" + profesor[1] + "%");
                        break;
                    case 3:
                        st = (PreparedStatement) con.prepareStatement("select noEmpleado from profesor where nombre like ? or apellido_p like ? or apellido_m like ?");
                        st.setString(1, "%" + profesor[0] + "%");
                        st.setString(2, "%" + profesor[1] + "%");
                        st.setString(3, "%" + profesor[2] + "%");
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Debes ingresar un nombre");
                        break;
                }
                rs = st.executeQuery();
                
                if(rs.next()){
                    no = rs.getInt("noEmpleado");
                }
        }catch(Exception e){
            
        }
        return no;
    }
    
    private void loaded(int no) {
        
        Connection con;
        PreparedStatement st;
        try {
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
            st = (PreparedStatement) con.prepareStatement("update login set nivel = ? where noEmpleado = ?");
            st.setInt(1, nivel);
            st.setInt(2, no);
            st.executeUpdate();

        } catch (Exception e) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambiar_permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambiar_permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambiar_permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambiar_permisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambiar_permisos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_aceptar;
    private javax.swing.JButton b_volver;
    private javax.swing.ButtonGroup bg_entrada;
    private javax.swing.ButtonGroup bg_niveles;
    private javax.swing.JTextField data_field;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rb_administrador;
    private javax.swing.JRadioButton rb_coordinador;
    private javax.swing.JRadioButton rb_no;
    private javax.swing.JRadioButton rb_nombre;
    private javax.swing.JRadioButton rb_profesor;
    // End of variables declaration//GEN-END:variables
}
