/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventana.editar_personales.getConection;
import static ventana.login.user_no;

/**
 *
 * @author Ale
 */
public class cambiar_contraseña extends javax.swing.JFrame {

    /**
     * Creates new form cambiar_permisos
     */
    private int nivel;

    public cambiar_contraseña() {
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/user2.png")).getImage());
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        contraseña = new javax.swing.JTextField();
        b_volver = new javax.swing.JButton();
        contraseña_nueva = new javax.swing.JTextField();
        b_aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contraseña.setBackground(new java.awt.Color(255, 255, 255));
        contraseña.setFont(new java.awt.Font("Anonymous Pro", 2, 24)); // NOI18N
        contraseña.setForeground(new java.awt.Color(0, 0, 0));
        contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraseña.setText("contraseña actual");
        contraseña.setMargin(new java.awt.Insets(0, 10, 0, 0));
        contraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseñaFocusGained(evt);
            }
        });
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 490, 52));

        b_volver.setBackground(new java.awt.Color(0, 0, 0));
        b_volver.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        b_volver.setForeground(new java.awt.Color(255, 255, 255));
        b_volver.setText("VOLVER");
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });
        jPanel2.add(b_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 230, 50));

        contraseña_nueva.setBackground(new java.awt.Color(255, 255, 255));
        contraseña_nueva.setFont(new java.awt.Font("Anonymous Pro", 2, 24)); // NOI18N
        contraseña_nueva.setForeground(new java.awt.Color(0, 0, 0));
        contraseña_nueva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraseña_nueva.setText("nueva contraseña");
        contraseña_nueva.setMargin(new java.awt.Insets(0, 10, 0, 0));
        contraseña_nueva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseña_nuevaFocusGained(evt);
            }
        });
        contraseña_nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseña_nuevaActionPerformed(evt);
            }
        });
        jPanel2.add(contraseña_nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 490, 52));

        b_aceptar.setBackground(new java.awt.Color(51, 0, 0));
        b_aceptar.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        b_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        b_aceptar.setText("ACEPTAR");
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(b_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 230, 50));

        jLabel1.setFont(new java.awt.Font("Chaparral Pro", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAMBIO DE CONTRASEÑA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 30));

        jTextField1.setBackground(new java.awt.Color(0, 51, 51));
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 40, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaFocusGained
        contraseña.setText("");
    }//GEN-LAST:event_contraseñaFocusGained

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        admin_tools main = new admin_tools();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b_volverActionPerformed

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
        cambiarContraseña();
        contraseña.setText("contraseña actual");
        contraseña_nueva.setText("contraseña nueva");
    }//GEN-LAST:event_b_aceptarActionPerformed

    private void contraseña_nuevaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseña_nuevaFocusGained
        contraseña_nueva.setText("");
    }//GEN-LAST:event_contraseña_nuevaFocusGained

    private void contraseña_nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseña_nuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseña_nuevaActionPerformed

    private void cambiarContraseña()
    {
        try {
            Connection con = null;
            con = getConection();

            PreparedStatement ps;
            int res;
            
            ps = (PreparedStatement) con.prepareStatement("update login set contraseña = ? where contraseña = ? and noEmpleado = ?");
            ps.setString(1, contraseña_nueva.getText());
            ps.setString(2, contraseña.getText());
            ps.setInt(3, user_no);
            
            res = ps.executeUpdate(); 

            JOptionPane.showMessageDialog(null, "¡Contraseña actualizada correctamente!");
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambiar_contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_aceptar;
    private javax.swing.JButton b_volver;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField contraseña_nueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
