/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventana.login.URL;
import static ventana.login.mysql_pass;
import static ventana.login.mysql_user;

/**
 *
 * @author Ale
 */
public class editar_personales extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public editar_personales() {
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/user2.png")).getImage());
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static Connection getConection() {
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);

        } catch (Exception e) {
            System.out.println(e);

        }
        return con;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panel_perfil = new javax.swing.JPanel();
        user_icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        change_pass = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        new_tel = new javax.swing.JTextField();
        new_email = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_perfil.setBackground(new java.awt.Color(204, 204, 204));
        panel_perfil.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        panel_perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N
        panel_perfil.add(user_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        change_pass.setBackground(new java.awt.Color(0, 102, 102));
        change_pass.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        change_pass.setText("CAMBIAR CONTRASEÑA");
        change_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_passActionPerformed(evt);
            }
        });
        jPanel2.add(change_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 320, 60));

        aceptar.setBackground(new java.awt.Color(102, 102, 102));
        aceptar.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 180, 60));

        new_tel.setBackground(new java.awt.Color(255, 255, 255));
        new_tel.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        new_tel.setForeground(new java.awt.Color(0, 0, 0));
        new_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        new_tel.setText(login.user_tel);
        jPanel2.add(new_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 570, 40));

        new_email.setBackground(new java.awt.Color(255, 255, 255));
        new_email.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        new_email.setForeground(new java.awt.Color(0, 0, 0));
        new_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        new_email.setText(login.user_email);
        new_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_emailActionPerformed(evt);
            }
        });
        jPanel2.add(new_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 570, 40));

        panel_perfil.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 600, 670));

        getContentPane().add(panel_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        try {
            Connection con = null;
            con = getConection();

            PreparedStatement ps;
            int res;
            
            ps = (PreparedStatement) con.prepareStatement("update login set correo = ? where correo = ?");
            ps.setString(1, new_email.getText());
            ps.setString(2, login.user_email);
            res = ps.executeUpdate(); //problem executing query, si se reciben los datos correctamente ¿podría ser la sintaxis?
            
            ps = (PreparedStatement) con.prepareStatement("update profesor set telefono = ? where telefono = ?");
            ps.setString(1, new_tel.getText());
            ps.setString(2, login.user_tel);
            res = ps.executeUpdate();
            System.out.println("Si se conectó");
            
            login.user_tel = new_tel.getText();
            login.user_email = new_email.getText().toUpperCase();
            JOptionPane.showMessageDialog(null, "¡Sus datos se han actualizado correctamente!");
            
            main main = new main();
            main.setVisible(true);
            this.setVisible(false);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void new_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_emailActionPerformed

    }//GEN-LAST:event_new_emailActionPerformed

    private void change_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_passActionPerformed
        cambiar_contraseña main = new cambiar_contraseña();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_change_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editar_personales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editar_personales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editar_personales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editar_personales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editar_personales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton change_pass;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField new_email;
    private javax.swing.JTextField new_tel;
    private javax.swing.JPanel panel_perfil;
    private javax.swing.JLabel user_icon;
    // End of variables declaration//GEN-END:variables
}
