/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import com.mysql.jdbc.Connection;
import java.awt.List;
import java.awt.event.ItemEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventana.login.URL;
import static ventana.login.mysql_pass;
import static ventana.login.mysql_user;
import static ventana.login.user_no;

/**
 *
 * @author Ale
 */
public class modificar_registros extends javax.swing.JFrame {

    boolean nombre_isEnabled = false;
    boolean apellido1_isEnabled = false;
    boolean apellido2_isEnabled = false;

    public String mat;
    private String listProf;
    private String listAlumnos;
    private String listNotificaciones;

    public modificar_registros() {
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/user2.png")).getImage());
        initComponents();
        this.setLocationRelativeTo(null);
//        binding();
    }

    public static Connection getConection() {
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);

        } catch (Exception e) {
            System.out.println(e);

        }
        return con;
    }

//    private void undefinnedOrder() {
//
//        try {
//            Connection con = null;
//            con = getConection();
//
//            PreparedStatement ps;
//            ResultSet res;
//            ps = (PreparedStatement) con.prepareStatement("select * from alumno");
////            ps.setString(1, data1.getText());
////            ps.setString(2, data2.getText());
//            res = ps.executeQuery();
//            if (res.next()) {
//
//
//            } else {
//                JOptionPane.showMessageDialog(null, "error al intentar acceder"); //no existen datos (puede ser porque el usuario o contraseña está mal)
//            }
//
//        } catch (Exception e) {
//            System.out.println("Error en try/catch");
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rb_group_selector = new javax.swing.ButtonGroup();
        rb_group_option = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_acciones = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        data_grupo = new javax.swing.JTextField();
        jalar_matricula = new javax.swing.JButton();
        buscar_matricula = new javax.swing.JButton();
        text_matricula_2 = new javax.swing.JTextField();
        text_matricula = new javax.swing.JTextField();
        check_apellido_m = new javax.swing.JCheckBox();
        check_apellido_p = new javax.swing.JCheckBox();
        check_nombre = new javax.swing.JCheckBox();
        text_datos = new javax.swing.JTextField();
        data_nombre = new javax.swing.JTextField();
        data_apellido1 = new javax.swing.JTextField();
        data_apellido2 = new javax.swing.JTextField();
        data_email = new javax.swing.JTextField();
        enviar_matricula = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rb_profesor = new javax.swing.JRadioButton();
        rb_alumno = new javax.swing.JRadioButton();
        rb_modificar = new javax.swing.JRadioButton();
        rb_eliminar = new javax.swing.JRadioButton();
        panel_listado = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Listado = new javax.swing.JTextArea();
        actualizar_listado_alumnos_boton = new javax.swing.JButton();
        data_listado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbutton_alumnos = new javax.swing.JRadioButton();
        rbutton_prof = new javax.swing.JRadioButton();

        jMenu1.setText("jMenu1");

        buttonGroup2.add(rbutton_alumnos);
        buttonGroup2.add(rbutton_prof);

        rb_group_selector.add(rb_profesor);
        rb_group_selector.add(rb_alumno);

        rb_group_option.add(rb_modificar);
        rb_group_option.add(rb_eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Anonymous Pro", 0, 11)); // NOI18N

        panel_acciones.setBackground(new java.awt.Color(102, 0, 51));
        panel_acciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aceptar.setBackground(new java.awt.Color(102, 102, 102));
        aceptar.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("VOLVER");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel3.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 210, 40));

        data_grupo.setBackground(new java.awt.Color(255, 255, 255));
        data_grupo.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        data_grupo.setForeground(new java.awt.Color(0, 0, 0));
        data_grupo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_grupo.setText("numero de grupo");
        data_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_grupoActionPerformed(evt);
            }
        });
        jPanel3.add(data_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 460, 40));

        jalar_matricula.setBackground(new java.awt.Color(102, 102, 102));
        jalar_matricula.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        jalar_matricula.setForeground(new java.awt.Color(255, 255, 255));
        jalar_matricula.setText("cargar");
        jalar_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalar_matriculaActionPerformed(evt);
            }
        });
        jPanel3.add(jalar_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 210, 40));

        buscar_matricula.setBackground(new java.awt.Color(102, 102, 102));
        buscar_matricula.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        buscar_matricula.setForeground(new java.awt.Color(255, 255, 255));
        buscar_matricula.setText("buscar matrícula");
        buscar_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_matriculaActionPerformed(evt);
            }
        });
        jPanel3.add(buscar_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 40));

        text_matricula_2.setBackground(new java.awt.Color(255, 255, 255));
        text_matricula_2.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        text_matricula_2.setForeground(new java.awt.Color(0, 0, 0));
        text_matricula_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_matricula_2.setText("matricula");
        text_matricula_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_matricula_2FocusGained(evt);
            }
        });
        jPanel3.add(text_matricula_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 210, 90));

        text_matricula.setEditable(false);
        text_matricula.setBackground(new java.awt.Color(255, 255, 255));
        text_matricula.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        text_matricula.setForeground(new java.awt.Color(0, 0, 0));
        text_matricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_matriculaActionPerformed(evt);
            }
        });
        jPanel3.add(text_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 210, 40));

        check_apellido_m.setForeground(new java.awt.Color(255, 255, 255));
        check_apellido_m.setText("Segundo Apellido");
        check_apellido_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_apellido_mActionPerformed(evt);
            }
        });
        jPanel3.add(check_apellido_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 160, -1));

        check_apellido_p.setForeground(new java.awt.Color(255, 255, 255));
        check_apellido_p.setText("Primer Apellido");
        check_apellido_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_apellido_pActionPerformed(evt);
            }
        });
        jPanel3.add(check_apellido_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 110, -1));

        check_nombre.setForeground(new java.awt.Color(255, 255, 255));
        check_nombre.setText("Nombre");
        check_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_nombreActionPerformed(evt);
            }
        });
        jPanel3.add(check_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, -1));

        text_datos.setBackground(new java.awt.Color(255, 255, 255));
        text_datos.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        text_datos.setForeground(new java.awt.Color(0, 0, 0));
        text_datos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_datos.setText("inserte dato seleccionado");
        text_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_datosActionPerformed(evt);
            }
        });
        jPanel3.add(text_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 460, 40));

        data_nombre.setBackground(new java.awt.Color(255, 255, 255));
        data_nombre.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        data_nombre.setForeground(new java.awt.Color(0, 0, 0));
        data_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_nombre.setText("nombre del alumno");
        data_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_nombreActionPerformed(evt);
            }
        });
        jPanel3.add(data_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 460, 40));

        data_apellido1.setBackground(new java.awt.Color(255, 255, 255));
        data_apellido1.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        data_apellido1.setForeground(new java.awt.Color(0, 0, 0));
        data_apellido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_apellido1.setText("primer apellido");
        data_apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_apellido1ActionPerformed(evt);
            }
        });
        jPanel3.add(data_apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 460, 40));

        data_apellido2.setBackground(new java.awt.Color(255, 255, 255));
        data_apellido2.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        data_apellido2.setForeground(new java.awt.Color(0, 0, 0));
        data_apellido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_apellido2.setText("segundo apellido");
        data_apellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_apellido2ActionPerformed(evt);
            }
        });
        jPanel3.add(data_apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 460, 40));

        data_email.setBackground(new java.awt.Color(255, 255, 255));
        data_email.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        data_email.setForeground(new java.awt.Color(0, 0, 0));
        data_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_email.setText("correo electrónico");
        data_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_emailActionPerformed(evt);
            }
        });
        jPanel3.add(data_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 460, 40));

        enviar_matricula.setBackground(new java.awt.Color(102, 102, 0));
        enviar_matricula.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        enviar_matricula.setForeground(new java.awt.Color(255, 255, 255));
        enviar_matricula.setText("enviar");
        enviar_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_matriculaActionPerformed(evt);
            }
        });
        jPanel3.add(enviar_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 210, 40));

        jLabel3.setFont(new java.awt.Font("Chaparral Pro", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MODIFICAR REGISTROS");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 460, 40));

        rb_profesor.setFont(new java.awt.Font("Anonymous Pro", 0, 18)); // NOI18N
        rb_profesor.setForeground(new java.awt.Color(255, 255, 255));
        rb_profesor.setText("PROFESOR");
        rb_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_profesorActionPerformed(evt);
            }
        });
        jPanel3.add(rb_profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        rb_alumno.setFont(new java.awt.Font("Anonymous Pro", 0, 18)); // NOI18N
        rb_alumno.setForeground(new java.awt.Color(255, 255, 255));
        rb_alumno.setSelected(true);
        rb_alumno.setText("ALUMNO");
        rb_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_alumnoActionPerformed(evt);
            }
        });
        jPanel3.add(rb_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        rb_modificar.setFont(new java.awt.Font("Anonymous Pro", 0, 18)); // NOI18N
        rb_modificar.setForeground(new java.awt.Color(255, 255, 255));
        rb_modificar.setSelected(true);
        rb_modificar.setText("MODIFICAR");
        rb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_modificarActionPerformed(evt);
            }
        });
        jPanel3.add(rb_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 130, -1));

        rb_eliminar.setFont(new java.awt.Font("Anonymous Pro", 0, 18)); // NOI18N
        rb_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        rb_eliminar.setText("ELIMINAR");
        rb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(rb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 110, -1));

        panel_acciones.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 550, 650));

        jTabbedPane1.addTab("PANEL DE ACCIONES", panel_acciones);

        panel_listado.setBackground(new java.awt.Color(0, 102, 0));
        panel_listado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Listado.setBackground(new java.awt.Color(0, 36, 67));
        Listado.setColumns(20);
        Listado.setFont(new java.awt.Font("Anonymous Pro", 0, 14)); // NOI18N
        Listado.setForeground(new java.awt.Color(255, 255, 255));
        Listado.setRows(5);
        jScrollPane2.setViewportView(Listado);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 540));

        actualizar_listado_alumnos_boton.setBackground(new java.awt.Color(0, 102, 102));
        actualizar_listado_alumnos_boton.setFont(new java.awt.Font("Chaparral Pro", 0, 18)); // NOI18N
        actualizar_listado_alumnos_boton.setForeground(new java.awt.Color(255, 255, 255));
        actualizar_listado_alumnos_boton.setText("ACTUALIZAR LISTADO");
        actualizar_listado_alumnos_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_listado_alumnos_botonActionPerformed(evt);
            }
        });
        jPanel4.add(actualizar_listado_alumnos_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 530, 40));

        data_listado.setBackground(new java.awt.Color(255, 255, 255));
        data_listado.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        data_listado.setForeground(new java.awt.Color(0, 0, 0));
        data_listado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_listadoActionPerformed(evt);
            }
        });
        jPanel4.add(data_listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 390, 40));

        jLabel4.setFont(new java.awt.Font("Anonymous Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BÚSQUEDA SELECTIVA");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 575, 390, 40));

        rbutton_alumnos.setFont(new java.awt.Font("Anonymous Pro", 0, 14)); // NOI18N
        rbutton_alumnos.setForeground(new java.awt.Color(255, 255, 255));
        rbutton_alumnos.setSelected(true);
        rbutton_alumnos.setText("ALUMNOS");
        jPanel4.add(rbutton_alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));

        rbutton_prof.setFont(new java.awt.Font("Anonymous Pro", 0, 14)); // NOI18N
        rbutton_prof.setForeground(new java.awt.Color(255, 255, 255));
        rbutton_prof.setText("PROFESORES");
        jPanel4.add(rbutton_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, -1, -1));

        panel_listado.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, 650));

        jTabbedPane1.addTab("  LISTADO ", panel_listado);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_grupoActionPerformed

    private void text_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_datosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_datosActionPerformed

    private void data_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_nombreActionPerformed

    private void data_apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_apellido1ActionPerformed

    private void data_apellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_apellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_apellido2ActionPerformed

    private void data_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_emailActionPerformed

    private void check_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_nombreActionPerformed
        //CheckBox nombre
        if (check_nombre.isSelected()) {
            nombre_isEnabled = true;
        } else {
            nombre_isEnabled = false;
        }
    }//GEN-LAST:event_check_nombreActionPerformed

    private void check_apellido_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_apellido_pActionPerformed
        if (check_nombre.isSelected()) {
            apellido1_isEnabled = true;
        } else {
            apellido1_isEnabled = false;
        }
    }//GEN-LAST:event_check_apellido_pActionPerformed

    private void check_apellido_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_apellido_mActionPerformed
        if (check_nombre.isSelected()) {
            apellido2_isEnabled = true;
        } else {
            apellido2_isEnabled = false;
        }
    }//GEN-LAST:event_check_apellido_mActionPerformed

    private void ma_buscar_alumno(){
        Connection con;
        PreparedStatement st;
        ResultSet rs;
        String state = "";
        String[] arr = text_datos.getText().split(" ");
        String state1 = "";
        String state2 = "";
        String state3 = "";
        //Problema en el que usando solo apellidos no se marca ningún where;
        try {
            if (nombre_isEnabled && apellido1_isEnabled && apellido2_isEnabled) {
                state1 = "nombre = '" + arr[0] + "' and ";
                state2 = "apellido_p = '" + arr[1] + "' and ";
                state3 = "apellido_m = '" + arr[2] + "' ";
            } else if (nombre_isEnabled && apellido1_isEnabled) {
                state1 = "nombre = '" + arr[0] + "' and ";
                state2 = "apellido_p = '" + arr[1] + "' ";
            } else if (nombre_isEnabled && apellido2_isEnabled) {
                state1 = "nombre = '" + arr[0] + "' and ";
                state2 = "apellido_m = '" + arr[1] + "' ";
            } else if (apellido1_isEnabled && apellido2_isEnabled) {
                state1 = "apellido_p = '" + arr[0] + "' and ";
                state2 = "apellido_m = '" + arr[1] + "' ";
            } else if (apellido2_isEnabled) {
                state1 = "apellido_m = '" + arr[0] + "' ";
            } else if (apellido1_isEnabled) {
                state1 = "apellido_p = '" + arr[0] + "' ";
            } else if (nombre_isEnabled) {
                state1 = "nombre = '" + arr[0] + "' ";
            } else {

            }

            state = "select matricula from alumno where " + state1 + state2 + state3;
            System.out.println(state);
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
            st = (PreparedStatement) con.prepareStatement(state);
            rs = st.executeQuery();
            if (rs.next()) {
                text_matricula.setText(rs.getString("matricula"));

            }
        } catch (Exception e) {

        }
    }
    
    private void ma_buscar_profesor(){
        Connection con;
        PreparedStatement st;
        ResultSet rs;
        String state = "";
        String[] arr = text_datos.getText().split(" ");
        String state1 = "";
        String state2 = "";
        String state3 = "";
        //Problema en el que usando solo apellidos no se marca ningún where;
        try {
            if (nombre_isEnabled && apellido1_isEnabled && apellido2_isEnabled) {
                state1 = "nombre = '" + arr[0] + "' and ";
                state2 = "apellido_p = '" + arr[1] + "' and ";
                state3 = "apellido_m = '" + arr[2] + "' ";
            } else if (nombre_isEnabled && apellido1_isEnabled) {
                state1 = "nombre = '" + arr[0] + "' and ";
                state2 = "apellido_p = '" + arr[1] + "' ";
            } else if (nombre_isEnabled && apellido2_isEnabled) {
                state1 = "nombre = '" + arr[0] + "' and ";
                state2 = "apellido_m = '" + arr[1] + "' ";
            } else if (apellido1_isEnabled && apellido2_isEnabled) {
                state1 = "apellido_p = '" + arr[0] + "' and ";
                state2 = "apellido_m = '" + arr[1] + "' ";
            } else if (apellido2_isEnabled) {
                state1 = "apellido_m = '" + arr[0] + "' ";
            } else if (apellido1_isEnabled) {
                state1 = "apellido_p = '" + arr[0] + "' ";
            } else if (nombre_isEnabled) {
                state1 = "nombre = '" + arr[0] + "' ";
            } else {

            }

            state = "select noEmpleado from profesor where " + state1 + state2 + state3;
            System.out.println(state);
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
            st = (PreparedStatement) con.prepareStatement(state);
            rs = st.executeQuery();
            if (rs.next()) {
                text_matricula.setText(rs.getString("noEmpleado"));

            }
        } catch (Exception e) {

        }
    }
    
    private void buscar_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_matriculaActionPerformed
        if(rb_alumno.isSelected()){
            ma_buscar_alumno();
        }else{
            ma_buscar_profesor();
        }
    }//GEN-LAST:event_buscar_matriculaActionPerformed

    private void text_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_matriculaActionPerformed

    private void jalar_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalar_matriculaActionPerformed
        if(rb_alumno.isSelected()){
            jalar_alumno();
        }else{
            jalar_profesor();
        }
    }//GEN-LAST:event_jalar_matriculaActionPerformed

    private void jalar_profesor(){
        text_matricula_2.setEditable(false);
        Connection con;
        PreparedStatement st;
        ResultSet rs;
        String state = "";

        try {

            state = "select nombre, apellido_p, apellido_m, login.correo, telefono from profesor, login where login.noEmpleado = ? and login.noEmpleado = profesor.noEmpleado";
            System.out.println(state);
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
            st = (PreparedStatement) con.prepareStatement(state);
            st.setString(1, text_matricula_2.getText());
            rs = st.executeQuery();
            if (rs.next()) {
                data_nombre.setText(rs.getString("nombre"));
                data_apellido1.setText(rs.getString("apellido_p"));
                data_apellido2.setText(rs.getString("apellido_m"));
                data_email.setText(rs.getString("login.correo"));
                data_grupo.setText(rs.getString("telefono"));
            } else {
                data_nombre.setText("numero de empleado inválido");
                data_apellido1.setText("numero de empleado inválido");
                data_apellido2.setText("numero de empleado inválido");
                data_email.setText("numero de empleado inválido");
                data_grupo.setText("numero de empleado inválido");
                text_matricula_2.setEditable(true);
            }

        } catch (Exception e) {

        }
    }
    
    private void jalar_alumno(){
        text_matricula_2.setEditable(false);
        Connection con;
        PreparedStatement st;
        ResultSet rs;
        String state = "";

        try {

            state = "select nombre, apellido_p, apellido_m, correo, noGrupo from alumno where matricula = ?";
            System.out.println(state);
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
            st = (PreparedStatement) con.prepareStatement(state);
            st.setString(1, text_matricula_2.getText());
            rs = st.executeQuery();
            if (rs.next()) {
                data_nombre.setText(rs.getString("nombre"));
                data_apellido1.setText(rs.getString("apellido_p"));
                data_apellido2.setText(rs.getString("apellido_m"));
                data_email.setText(rs.getString("correo"));
                data_grupo.setText(rs.getString("noGrupo"));
            } else {
                data_nombre.setText("matricula inválida");
                data_apellido1.setText("matricula inválida");
                data_apellido2.setText("matricula inválida");
                data_email.setText("matricula inválida");
                data_grupo.setText("matricula inválida");
                text_matricula_2.setEditable(true);
            }

        } catch (Exception e) {

        }
    }
    
    private void enviar_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_matriculaActionPerformed
        if (rb_modificar.isSelected()) {
            updateData();
        } else {
            deleteMatricula();
        }
    }//GEN-LAST:event_enviar_matriculaActionPerformed

    public void deleteMatricula() {
        if (rb_alumno.isSelected()) {

            text_matricula_2.setEditable(true);
            Connection con;
            PreparedStatement st;
            int rs;
            String state = "";

            try {
                System.out.println(state);
                con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
                st = (PreparedStatement) con.prepareStatement("delete from alumno where matricula = ?");
                st.setString(1, text_matricula_2.getText());
                rs = st.executeUpdate();


                text_matricula_2.setText("matrícula");

            } catch (Exception e) {

            }
        } else {

            text_matricula_2.setEditable(true);
            Connection con;
            PreparedStatement st;
            int rs;
            String state = "";

            try {
                System.out.println(state);
                con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
                st = (PreparedStatement) con.prepareStatement("delete from profesor where noEmpleado = ?");
                st.setString(1, text_matricula_2.getText());
                rs = st.executeUpdate();

                text_matricula_2.setText("noEmpleado");

            } catch (Exception e) {

            }
        }
    }

    public void updateData() {
        
        if (rb_alumno.isSelected()) {

            text_matricula_2.setEditable(true);
            Connection con;
            PreparedStatement st;
            int rs;
            String state = "";

            try {
                System.out.println(state);
                con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
                st = (PreparedStatement) con.prepareStatement("update alumno set nombre = ? where matricula = ?");
                st.setString(1, data_nombre.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                st = (PreparedStatement) con.prepareStatement("update alumno set apellido_p = ? where matricula = ?");
                st.setString(1, data_apellido1.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                st = (PreparedStatement) con.prepareStatement("update alumno set apellido_m = ? where matricula = ?");
                st.setString(1, data_apellido2.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                st = (PreparedStatement) con.prepareStatement("update alumno set correo = ? where matricula = ?");
                st.setString(1, data_email.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                st = (PreparedStatement) con.prepareStatement("update alumno set noGrupo = ? where matricula = ?");
                st.setString(1, data_grupo.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                text_matricula_2.setText("matrícula");
                data_nombre.setText("nombre alumno");
                data_apellido1.setText("primer apellido");
                data_apellido2.setText("segundo apellido");
                data_email.setText("correo electrónico");
                data_grupo.setText("numero de grupo");

            } catch (Exception e) {

            }
        } else {

            text_matricula_2.setEditable(true);
            Connection con;
            PreparedStatement st;
            int rs;
            String state = "";

            try {
                System.out.println(state);
                con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
                st = (PreparedStatement) con.prepareStatement("update profesor set nombre = ? where noEmpleado = ?");
                st.setString(1, data_nombre.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                st = (PreparedStatement) con.prepareStatement("update profesor set apellido_p = ? where noEmpleado = ?");
                st.setString(1, data_apellido1.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                st = (PreparedStatement) con.prepareStatement("update profesor set apellido_m = ? where noEmpleado = ?");
                st.setString(1, data_apellido2.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                st = (PreparedStatement) con.prepareStatement("update login set correo = ? where noEmpleado = ?");
                st.setString(1, data_email.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                st = (PreparedStatement) con.prepareStatement("update profesor set telefono = ? where noEmpleado = ?");
                st.setString(1, data_grupo.getText());
                st.setString(2, text_matricula_2.getText());
                rs = st.executeUpdate();

                text_matricula_2.setText("noEmpleado");
                data_nombre.setText("nombre profesor");
                data_apellido1.setText("primer apellido");
                data_apellido2.setText("segundo apellido");
                data_email.setText("correo electrónico");
                data_grupo.setText("telefono");

            } catch (Exception e) {

            }
        }

    }


    private void actualizar_listado_alumnos_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_listado_alumnos_botonActionPerformed
        loadList(rbutton_alumnos.isSelected());
    }//GEN-LAST:event_actualizar_listado_alumnos_botonActionPerformed

    private void data_listadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_listadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_listadoActionPerformed

    private void rb_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_profesorActionPerformed
        text_matricula_2.setText("n° empleado");
        data_nombre.setText("nombre profesor");
        data_apellido1.setText("primer apellido");
        data_apellido2.setText("segundo apellido");
        data_email.setText("telefono");
        data_grupo.setText("numero de grupo");
        data_grupo.setVisible(false);
    }//GEN-LAST:event_rb_profesorActionPerformed

    private void rb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_modificarActionPerformed
        data_nombre.setVisible(true);
        data_apellido1.setVisible(true);
        data_apellido2.setVisible(true);
        data_email.setVisible(true);
        data_grupo.setVisible(true);
        jalar_matricula.setVisible(true);
        enviar_matricula.setText("enviar");
    }//GEN-LAST:event_rb_modificarActionPerformed

    private void rb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_eliminarActionPerformed
        data_nombre.setVisible(false);
        data_apellido1.setVisible(false);
        data_apellido2.setVisible(false);
        data_email.setVisible(false);
        data_grupo.setVisible(false);
        jalar_matricula.setVisible(false);
        enviar_matricula.setText("eliminar");
        
    }//GEN-LAST:event_rb_eliminarActionPerformed

    private void rb_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_alumnoActionPerformed
        text_matricula_2.setText("matrícula");
        data_nombre.setText("nombre alumno");
        data_apellido1.setText("primer apellido");
        data_apellido2.setText("segundo apellido");
        data_email.setText("correo electrónico");
        data_grupo.setText("numero de grupo");
        if (rb_eliminar.isSelected()==false){
            data_grupo.setVisible(true);
        }
    }//GEN-LAST:event_rb_alumnoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        admin_tools main = new admin_tools();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aceptarActionPerformed

    private void text_matricula_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_matricula_2FocusGained
        text_matricula_2.setText("");
    }//GEN-LAST:event_text_matricula_2FocusGained

    public void loadList(boolean target) {

        listProf = "n°   NOMBRE         APELLIDO P.    APELLIDO M.\n";
        listAlumnos = "MATRICULA GRUPO     NOMBRE         APELLIDO P.    APELLIDO M.\n";
        Connection con;
        PreparedStatement st;
        ResultSet rs;
        String crow;

        if (target) {
            try {
                System.out.println("Flag 1");
                con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
                st = (PreparedStatement) con.prepareStatement("select nombre, apellido_p, apellido_m, noGrupo, matricula from alumno where nombre like ? or apellido_p like ? or apellido_m like ?");
                System.out.println("Flag 2: " + data_listado.getText());
                st.setString(1, "%" + data_listado.getText() + "%");
                st.setString(2, "%" + data_listado.getText() + "%");
                st.setString(3, "%" + data_listado.getText() + "%");
                System.out.println("Flag 3");
                rs = st.executeQuery();
                System.out.println("Flag 4");
                while (rs.next()) {
                    System.out.println("Flag 5");
                    crow = normalize(rs.getString("matricula"), 10) + normalize(rs.getString("noGrupo"), 10) + normalize(rs.getString("nombre"), 15) + normalize(rs.getString("apellido_p"), 15) + normalize(rs.getString("apellido_m"), 10);
                    System.out.println("termino, going next");
                    listAlumnos = listAlumnos + crow;
                    Listado.setText(listAlumnos);
                    listAlumnos = listAlumnos + "\n\n";
                    System.out.println("Flag 6");
                }

            } catch (Exception e) {
                System.out.println(e);
            }
        } else {

            try {
                con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);
                st = (PreparedStatement) con.prepareStatement("select nombre, apellido_p, apellido_m, noEmpleado from profesor where nombre like ? or apellido_p like ? or apellido_m like ?");
                st.setString(1, "%" + data_listado.getText() + "%");
                st.setString(2, "%" + data_listado.getText() + "%");
                st.setString(3, "%" + data_listado.getText() + "%");
                rs = st.executeQuery();
                while (rs.next()) {
                    crow = normalize(rs.getString("noEmpleado"), 5) + normalize(rs.getString("nombre"), 15) + normalize(rs.getString("apellido_p"), 15) + normalize(rs.getString("apellido_m"), 10);
                    System.out.println("termino, going next");
                    listProf = listProf + crow;
                    Listado.setText(listProf);
                    listProf = listProf + "\n\n";
                }

            } catch (Exception e) {
                System.out.println(e);
            }

        }

    }

    public String normalize(String entrada, int length) {
        while (entrada.length() < length) {
            entrada = entrada + " ";
        }
        return entrada;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificar_registros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificar_registros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificar_registros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificar_registros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificar_registros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Listado;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton actualizar_listado_alumnos_boton;
    private javax.swing.JButton buscar_matricula;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox check_apellido_m;
    private javax.swing.JCheckBox check_apellido_p;
    private javax.swing.JCheckBox check_nombre;
    private javax.swing.JTextField data_apellido1;
    private javax.swing.JTextField data_apellido2;
    private javax.swing.JTextField data_email;
    private javax.swing.JTextField data_grupo;
    private javax.swing.JTextField data_listado;
    private javax.swing.JTextField data_nombre;
    private javax.swing.JButton enviar_matricula;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jalar_matricula;
    private javax.swing.JPanel panel_acciones;
    private javax.swing.JPanel panel_listado;
    private javax.swing.JRadioButton rb_alumno;
    private javax.swing.JRadioButton rb_eliminar;
    private javax.swing.ButtonGroup rb_group_option;
    private javax.swing.ButtonGroup rb_group_selector;
    private javax.swing.JRadioButton rb_modificar;
    private javax.swing.JRadioButton rb_profesor;
    private javax.swing.JRadioButton rbutton_alumnos;
    private javax.swing.JRadioButton rbutton_prof;
    private javax.swing.JTextField text_datos;
    private javax.swing.JTextField text_matricula;
    private javax.swing.JTextField text_matricula_2;
    // End of variables declaration//GEN-END:variables
}
