/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventana.login.URL;
import static ventana.login.mysql_pass;
import static ventana.login.mysql_user;

/**
 *
 * @author Ale
 */
public class registrar_alumnos extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public registrar_alumnos() {
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/user2.png")).getImage());
        initComponents();
        this.setLocationRelativeTo(null);
        data_email.setVisible(false);
    }

    public static Connection getConection() {
        Connection con = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, mysql_user, mysql_pass);

        } catch (Exception e) {
            System.out.println(e);

        }
        return con;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        correo_rb = new javax.swing.ButtonGroup();
        panel_perfil = new javax.swing.JPanel();
        user_icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        registrar = new javax.swing.JButton();
        data_email = new javax.swing.JTextField();
        apellido_m = new javax.swing.JTextField();
        apellido_p = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        rb_existente = new javax.swing.JRadioButton();
        rb_automatico = new javax.swing.JRadioButton();

        jMenu1.setText("jMenu1");

        correo_rb.add(rb_automatico);
        correo_rb.add(rb_existente);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_perfil.setBackground(new java.awt.Color(204, 204, 204));
        panel_perfil.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        panel_perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N
        panel_perfil.add(user_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrar.setBackground(new java.awt.Color(0, 73, 95));
        registrar.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("REGISTRAR");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel2.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 360, 60));

        data_email.setBackground(new java.awt.Color(255, 255, 255));
        data_email.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        data_email.setForeground(new java.awt.Color(0, 0, 0));
        data_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                data_emailFocusGained(evt);
            }
        });
        jPanel2.add(data_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 570, 40));

        apellido_m.setBackground(new java.awt.Color(255, 255, 255));
        apellido_m.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        apellido_m.setForeground(new java.awt.Color(0, 0, 0));
        apellido_m.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido_m.setText("segundo apellido");
        apellido_m.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellido_mFocusGained(evt);
            }
        });
        jPanel2.add(apellido_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 570, 40));

        apellido_p.setBackground(new java.awt.Color(255, 255, 255));
        apellido_p.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        apellido_p.setForeground(new java.awt.Color(0, 0, 0));
        apellido_p.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido_p.setText("primer apellido");
        apellido_p.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellido_pFocusGained(evt);
            }
        });
        jPanel2.add(apellido_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 570, 40));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setText("nombre");
        nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFocusGained(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 570, 40));

        aceptar.setBackground(new java.awt.Color(102, 102, 102));
        aceptar.setFont(new java.awt.Font("Chaparral Pro", 0, 24)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("VOLVER");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, 60));

        rb_existente.setFont(new java.awt.Font("Anonymous Pro", 0, 14)); // NOI18N
        rb_existente.setForeground(new java.awt.Color(255, 255, 255));
        rb_existente.setText("USAR EXIXTENTE");
        rb_existente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_existenteActionPerformed(evt);
            }
        });
        jPanel2.add(rb_existente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        rb_automatico.setFont(new java.awt.Font("Anonymous Pro", 0, 14)); // NOI18N
        rb_automatico.setForeground(new java.awt.Color(255, 255, 255));
        rb_automatico.setSelected(true);
        rb_automatico.setText("CREAR E-MAIL AUTOMÁTICAMENTE");
        rb_automatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_automaticoActionPerformed(evt);
            }
        });
        jPanel2.add(rb_automatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        panel_perfil.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 600, 670));

        getContentPane().add(panel_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private String email_gen(){
        String deliver;
        if(rb_automatico.isSelected()){
            deliver = nombre.getText().charAt(0) + "." + apellido_p.getText() + "@cetys.edu.mx";
            return deliver.toLowerCase();
        }else {
            return data_email.getText();
        }
    }
    
    
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        Random randomGenerator = new Random();
		int randomInt = randomGenerator.nextInt(3) + 1;
        try {
            Connection con = null;
            con = getConection();
            PreparedStatement ps;
            int res;
            
            ps = (PreparedStatement) con.prepareStatement("insert into alumno (nombre, apellido_p, apellido_m, correo, noGrupo) values(?,?,?,?,?)");
            ps.setString(1, nombre.getText());
            ps.setString(2, apellido_p.getText());
            ps.setString(3, apellido_m.getText());
            ps.setString(4, email_gen());
            ps.setInt(5, randomInt);
            
            res = ps.executeUpdate(); 

            JOptionPane.showMessageDialog(null, "¡Se ha creado el alumno correctamente!");
            
            nombre.setText("nombre");
            apellido_p.setText("primer apellido");
            apellido_m.setText("segundo apellido");
            data_email.setText("");
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al crear el usuario, por favor, verifique los datos\nerror\n" + e);
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed

    }//GEN-LAST:event_nombreActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        admin_tools main = new admin_tools();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aceptarActionPerformed

    private void rb_existenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_existenteActionPerformed
        data_email.setVisible(true);
    }//GEN-LAST:event_rb_existenteActionPerformed

    private void rb_automaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_automaticoActionPerformed
        data_email.setVisible(false);
    }//GEN-LAST:event_rb_automaticoActionPerformed

    private void nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusGained
        nombre.setText("");
    }//GEN-LAST:event_nombreFocusGained

    private void apellido_pFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellido_pFocusGained
        apellido_p.setText("");
    }//GEN-LAST:event_apellido_pFocusGained

    private void apellido_mFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellido_mFocusGained
        apellido_m.setText("");
    }//GEN-LAST:event_apellido_mFocusGained

    private void data_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_emailFocusGained
        data_email.setText("");
    }//GEN-LAST:event_data_emailFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrar_alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrar_alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField apellido_m;
    private javax.swing.JTextField apellido_p;
    private javax.swing.ButtonGroup correo_rb;
    private javax.swing.JTextField data_email;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel panel_perfil;
    private javax.swing.JRadioButton rb_automatico;
    private javax.swing.JRadioButton rb_existente;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel user_icon;
    // End of variables declaration//GEN-END:variables
}
